name: Lint & Test Go

on:
  workflow_call:
    inputs:
      go-test-args:
        description: "Arguments to pass to `go test`"
        type: string
        required: false
      try-build:
        description: "Attempt to build the project"
        type: boolean
        required: false
        default: true

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23, 1.24]
        os: [ubuntu-publish, windows-publish, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure Git # required for golangci-lint on Windows
        if: startsWith(matrix.os, 'windows')
        shell: bash
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: SiaFoundation/workflows/.github/actions/go-test@master
        with:
          go-test-args: ${{ inputs.go-test-args }}
      - name: Build
        if: ${{ inputs.try-build }}
        shell: bash
        run: |
          go mod download
          go build -o bin/ ./...

  success: # Use in branch rulesets to ensure all matrix jobs completed successfully
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success!"
